### PR TITLE
sdk: bump version to latest v2.8.x

### PR DESCRIPTION
**Pull request by bzz**
Part of the https://github.com/bblfsh/client-go/issues/102

### CODE REVIEW

**Comment by dennwc** [comment]
Updating and cutting releases for each driver is painful, so let's wait for tracing.

**Comment by bzz** [comment]
>  so let's wait for tracing.

do you mean to wait for another SDK release that includes https://github.com/bblfsh/sdk/pull/330 and then bumping it up everywhere?

**Comment by dennwc** [comment]
As mentioned, I'll hijack this PR and will update it in a different way to get a bit more tracing.

**Comment by bzz** [comment]
👍 closed in favor of https://github.com/bblfsh/go-driver/pull/35

**Pull request closed without merging**
